In [27]:
import numpy as np

grid_py = [[0,0,0,0,0,0,0,0],
        [0,0,0,1,0,0,0,0],
        [0,1,0,1,0,0,0,0],
        [0,0,1,1,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0]
        ]

def show_py(grid_py):
    for row in grid_py[1:-1]:
        print(row[1:-1])
    print()


def compute_neighbours_py(grid_py):
    (rows, cols) = len(grid_py), len(grid_py[0])
    neighbours = [[0] * cols for i in range(rows)]
    for row in range(1, rows-1):
        for col in range(1, cols-1):
            neighbours[row][col] = (grid_py[row-1][col-1] + grid_py[row-1][col] + grid_py[row-1][col+1] +
                                    grid_py[row][col-1] +                      grid_py[row][col+1] +
                                    grid_py[row+1][col-1] + grid_py[row+1][col] + grid_py[row+1][col+1])

    return neighbours

def update_py(grid_py):
    (rows, cols) = len(grid_py), len(grid_py[0])
    neighbours = compute_neighbours_py(grid_py)
    for row in range(1, rows-1):
        for col in range(1, cols-1):
            if grid_py[row][col] == 1 and (neighbours[row][col] < 2 or neighbours[row][col] > 3):
                grid_py[row][col] = 0
            elif grid_py[row][col] == 0 and neighbours[row][col] == 3:
                grid_py[row][col] = 1


show_py(grid_py)
update_py(grid_py)
show_py(grid_py)
update_py(grid_py)
show_py(grid_py)



[0, 0, 1, 0, 0, 0]
[1, 0, 1, 0, 0, 0]
[0, 1, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]

[0, 1, 0, 0, 0, 0]
[0, 0, 1, 1, 0, 0]
[0, 1, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]

[0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0]
[0, 1, 1, 1, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]



In [34]:
# This is the numpy implementation

grid_py = [[0,0,0,0,0,0,0,0],
        [0,0,0,1,0,0,0,0],
        [0,1,0,1,0,0,0,0],
        [0,0,1,1,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0]
        ]

grid = np.array(grid_py)
# grid = np.random.randint(0,2, (256, 512))

def show(grid):
    print(grid)

def compute_neighbour(grid):
    neighbours = np.zeros(grid.shape, np.int32)

    neighbours[1:-1,1:-1] = (grid[0:-2,0:-2] + grid[0:-2,1:-1] + grid[0:-2,2:] +
                              grid[1:-1,0:-2] +                      grid[1:-1,2:] +
                              grid[2:,0:-2] + grid[2:,1:-1] + grid[2:,2:])

    print(neighbours)

    return neighbours


def update(grid):
    neighbours = compute_neighbour(grid)
    # Rule 1: If the cell is 1 and has less than 2 or more than 3 neighbors, set it to 0.
    grid = np.where((grid == 1) & ((neighbours < 2) | (neighbours > 3)), 0, grid)

    # Rule 2: If the cell is 0 and has exactly 3 neighbors, set it to 1.
    grid = np.where((grid == 0) & (neighbours == 3), 1, grid)



show(grid)
update(grid)
show(grid)




[[0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 1 3 1 2 0 0 0]
 [0 1 5 3 3 0 0 0]
 [0 2 3 2 2 0 0 0]
 [0 1 2 2 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
