# Class 1

This class is focused upon building efficient python scripts and handling data in numpy.

In [1]:
import numpy as np


# Numpy creates c-represented arrays that efficiently lie within system memory (no python typical object based saving)
x = np.array([[1,2,3], [4,5,6]])
print(x) # print whole array
print(x[1]) # print part of array
print(x[1,2]) # print specific part of array
print(x[0:2,2:3])  # print slice


vec = ([1,2,3])
# access single items
print(vec[1]) # prints item 1 of vec
print(vec[0:2]) # prints subarray
print(vec[2:]) # prints open end of array

[[1 2 3]
 [4 5 6]]
[4 5 6]
6
[[3]
 [6]]
2
[1, 2]
[3]


In [104]:
# Playing with arrays

np.zeros(4) # not referenced and therefor released to garbage collector instantly

np.arange(4) # not referenced and therefor released to garbage collector instantly

np.zeros((10,10)) # not referenced and therefor released to garbage collector instantly

int32_array = np.array([[1,2,3],[1,2,3]], np.int32) # specify datatype
int32_array.dtype # can be used for analysis
int32_array.ndim
int32_array.shape
int32_array.size

int32_array = np.array([[1,2,3],[1,2,3]], np.int32)

y = int32_array.reshape(6) # reshape to 1dim - USES SAME MEMORY!!!
# int32_array.shape[0,1] = 32 # WILL CHANGE BOTH Y AND INT32_ARRAY



In [124]:
# Exercise in class

def print_bytes(arr, idx):
    # Error handling
    if idx[0] >= arr.shape[0] or idx[1] > arr.shape[1]:
        print("Out of bounds")
        return

    bytesize = arr.itemsize  # Get the size of each element in bytes

    raw_byte_array = arr.byteswap().tobytes()

    # Calculate the byte offset for the given index
    element_offset = bytesize * (idx[1] + idx[0] * arr.shape[1])

    # Print the raw byte at the calculated offset
    raw_byte = raw_byte_array[element_offset:element_offset + bytesize]  # Slice for the raw byte(s) of the element
    print(f"Raw byte(s) at index ({idx[0]}, {idx[1]}): {raw_byte}")
    return

arr = np.array([[1,2,3],[4,5,6]], np.int16)
idx = (0,3)
print_bytes(arr, idx)



Raw byte(s) at index (0, 3): b'\x00\x04'


In [57]:
b = np.array([1,1,3,3],[2,2,4,4])
print(np.hsplit(b,2))
print(np.vsplit(b,2))

a = np.array([1,2,3,4],[5,6,7,8])
b = a[0,:]
c = a[1,:].copy()
c[0] = 23
print(c)
print(b)

6


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.shape
row_vec = a[np.newaxis,:]
row_vec.shape
col_vec = a[:,np.newaxis]
col_vec.shape

row_vec = np.expand_dims(a, axis=0)
row_vec
col_vec = np.expand_dims(a, axis=1)
col_vec



In [7]:
# Exercise 2 - vector normalization without numpy

from random import random

data = [random() for _ in range(30000000)]

mean = sum(data) / len(data)
result = [data[i] - mean for i in range(len(data))]


In [6]:
# Exercise 2 - vector normalization with numpy FAST - dont use for loops with numpy

# numpy array with 3000000 randoms
data_np = np.random.random(30000000)

mean_np = data_np.sum() / len(data_np)
result_np = data_np - mean_np



In [17]:
a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

rows = np.array([[0,0], [2,2]])
cols = np.array([[0,0], [2,3]])

a[rows, cols]
a[rows]

a[np.array([1, -1])]

a < 6
a[a<6]
(a>5) | (a==5)
a[(a>5) | (a==5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
# Alternative durch Numpy

a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

np.where(a <6, a, 0)
np.nonzero(a<6)


(array([0, 0, 0, 0, 1]), array([0, 1, 2, 3, 0]))