In [27]:
import numpy as np

grid_py = [[0,0,0,0,0,0,0,0],
        [0,0,0,1,0,0,0,0],
        [0,1,0,1,0,0,0,0],
        [0,0,1,1,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0]
        ]

def show_py(grid_py):
    for row in grid_py[1:-1]:
        print(row[1:-1])
    print()


def compute_neighbours_py(grid_py):
    (rows, cols) = len(grid_py), len(grid_py[0])
    neighbours = [[0] * cols for i in range(rows)]
    for row in range(1, rows-1):
        for col in range(1, cols-1):
            neighbours[row][col] = (grid_py[row-1][col-1] + grid_py[row-1][col] + grid_py[row-1][col+1] +
                                    grid_py[row][col-1] +                      grid_py[row][col+1] +
                                    grid_py[row+1][col-1] + grid_py[row+1][col] + grid_py[row+1][col+1])

    return neighbours

def update_py(grid_py):
    (rows, cols) = len(grid_py), len(grid_py[0])
    neighbours = compute_neighbours_py(grid_py)
    for row in range(1, rows-1):
        for col in range(1, cols-1):
            if grid_py[row][col] == 1 and (neighbours[row][col] < 2 or neighbours[row][col] > 3):
                grid_py[row][col] = 0
            elif grid_py[row][col] == 0 and neighbours[row][col] == 3:
                grid_py[row][col] = 1


show_py(grid_py)
update_py(grid_py)
show_py(grid_py)
update_py(grid_py)
show_py(grid_py)



[0, 0, 1, 0, 0, 0]
[1, 0, 1, 0, 0, 0]
[0, 1, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]

[0, 1, 0, 0, 0, 0]
[0, 0, 1, 1, 0, 0]
[0, 1, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]

[0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0]
[0, 1, 1, 1, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]



In [4]:
import numpy as np

grid_py = [[0,0,0,0,0,0,0,0],
        [0,0,0,1,0,0,0,0],
        [0,1,0,1,0,0,0,0],
        [0,0,1,1,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0]
        ]

grid = np.array(grid_py)

# grid = np.random.randint(0,2, (256, 512))

def show(grid):
    print(grid)

def compute_neighbour(grid):
    neighbours = np.zeros(grid.shape, np.int32)

    neighbours[1:-1,1:-1] = (   grid[0:-2 ,0:-2] +     grid[0:-2,1:-1] +    grid[0:-2,2:] +
                                grid[1:-1 ,0:-2] +                          grid[1:-1,2:] +
                                grid[2:   ,0:-2] +     grid[2:  ,1:-1] +    grid[2:  ,2:])
    return neighbours


def update(grid):
    neighbours = compute_neighbour(grid)
    # Rule 1: If the cell is 1 and has less than 2 or more than 3 neighbors, set it to 0.
    newgrid = np.where((grid == 1) & ((neighbours < 2) | (neighbours > 3)), 0, grid)

    # Rule 2: If the cell is 0 and has exactly 3 neighbors, set it to 1.
    newgrid = np.where((grid == 0) & (neighbours == 3), 1, grid)

    grid = newgrid

def update_prof1(grid):
    neighors =compute_neighbour(grid)
    rule1 = np.argwhere((grid ==1 ) & (neighors < 2))
    rule2 = np.argwhere((grid == 1) & (neighors == 2 | neighors == 3))
    rule3 = np.argwhere((grid == 1) & (neighors > 3))
    rule4 = np.argwhere((grid == 0) & (neighors == 3))

    grid[tuple([rule1[:,i] for i in range(2)])] = 0
    grid[tuple([rule2[:,i] for i in range(2)])] = 0
    grid[tuple([rule3[:,i] for i in range(2)])] = 0
    grid[tuple([rule4[:,i] for i in range(2)])] = 0

def update_prof2(grid):
    neighors =compute_neighbour(grid)
    grid_1d = grid.ravel()
    neighors_1d = grid.ravel()
    rule1 = np.argwhere((grid_1d ==1 ) & (neighors_1d < 2))
    rule2 = np.argwhere((grid_1d == 1) & (neighors_1d == 2 | neighors_1d == 3))
    rule3 = np.argwhere((grid_1d == 1) & (neighors_1d > 3))
    rule4 = np.argwhere((grid_1d == 0) & (neighors_1d == 3))

    grid_1d[rule1] = 0
    grid_1d[rule2] = grid_1d[rule2]
    grid_1d[rule3] = 0
    grid_1d[rule4] = 1

    grid[0,:] = grid[-1, :] = grid[:, 0] = grid [:, -1] = 0


def update_prof3(grid):
    neighors =compute_neighbour(grid)
    rule1 = np.nonzero((grid ==1 ) & (neighors < 2))
    rule2 = np.nonzero((grid == 1) & (neighors == 2 | neighors == 3))
    rule3 = np.nonzero((grid == 1) & (neighors > 3))
    rule4 = np.nonzero((grid == 0) & (neighors == 3))

    grid[rule1] = 0
    grid[rule2] = grid[rule2]
    grid[rule3] = 0
    grid[rule4] = 1

def update_prof4(grid):
    neighbours =compute_neighbour(grid)
    birth = (grid == 0) & (neighbours == 3)
    survive = ((grid == 1) & (neighbours == 2) or (neighbours == 2))

    grid[...] = 0
    grid[birth | survive] = 1


def changegrid(grid):
    print(id(grid))
    grid = np.where(grid == 1, grid, 0)


for i in range(5):
    show(grid)
    grid = update(grid)
    show(grid)


[[0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
None
None


AttributeError: 'NoneType' object has no attribute 'shape'