In [1]:
import numpy as np
import time

grid_py = [[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]

grid = np.array(grid_py)
#grid = np.random.randint(0, 2, (256, 512))


def show(grid):
    for row in grid[1:-1]:
        print(row[1:-1])
    print()

def compute_neighbors(grid):
    neighbors = np.zeros(grid.shape, np.int32)
    neighbors[1:-1, 1:-1] = (grid[0:-2, 0:-2] + grid[0:-2, 1:-1] + grid[0:-2, 2:] +
                             grid[1:-1, 0:-2]                    + grid[1:-1, 2:] +
                             grid[2:  , 0:-2] + grid[2:  , 1:-1] + grid[2:  , 2:])
    return neighbors

def update(grid):
    (rows, cols) = len(grid), len(grid[0])
    neighbors = compute_neighbors(grid)
    print(id(grid))

    for row in range(1, rows-1):
        for col in range(1, cols-1):
            if grid[row][col] == 1 and (neighbors[row][col] < 2 or neighbors[row][col] > 3):
                grid[row][col] = 0
            elif grid[row][col] == 0 and neighbors[row][col] == 3:
                grid[row][col] = 1
            #elif grid[row][col] == 1 and (neighbors[row][col] == 2 or neighbors[row][col] == 3):
            #    grid[row][col] == 1


#show(grid)
print(id(grid))
for i in range(5):
    start = time.time()
    update(grid)
    end = time.time()
    print(f"game of life update {i}: {end - start} s")
    show(grid)

139895407973584
139895407973584
game of life update 0: 8.845329284667969e-05 s
[0 1 0 0 0 0]
[0 0 1 1 0 0]
[0 1 1 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]

139895407973584
game of life update 1: 5.841255187988281e-05 s
[0 0 1 0 0 0]
[0 0 0 1 0 0]
[0 1 1 1 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]

139895407973584
game of life update 2: 5.5789947509765625e-05 s
[0 0 0 0 0 0]
[0 1 0 1 0 0]
[0 0 1 1 0 0]
[0 0 1 0 0 0]
[0 0 0 0 0 0]

139895407973584
game of life update 3: 5.626678466796875e-05 s
[0 0 0 0 0 0]
[0 0 0 1 0 0]
[0 1 0 1 0 0]
[0 0 1 1 0 0]
[0 0 0 0 0 0]

139895407973584
game of life update 4: 5.555152893066406e-05 s
[0 0 0 0 0 0]
[0 0 1 0 0 0]
[0 0 0 1 1 0]
[0 0 1 1 0 0]
[0 0 0 0 0 0]

